config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  before_save :set_tweeted_time, if: :new_record?
  validates :message, presence: true, length: { in: 1..140 }

  private

  def set_tweeted_time
    self.tdate = Time.current
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all.order(id: "DESC")
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render new_tweet_path
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(tweet_params)
    redirect_to root_path
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tkhs01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/edit.html.erb
<h1>Edit your tweet</h1>
<%= form_for @tweet, url: {action: :update} do |f| %>
  <%= f.label :message, '本文'%>
  <%= f.text_field :message%>
  <br>
  <%= f.submit '更新'%>
<% end %>

app/views/tweets/index.html.erb
<div class="container">
  <div class="content-profile">
    <h2 class="display_name">近畿大学</h2>
    <p class="user_name">@kinkidaigakuPR</p>
    <p class="description">
      近畿大学のTwitter公式アカウントです。
      気象警報による休講情報や、お得なランチ情報など、大学に関する情報を発信します。
      マグロに関するツイート多め🐟学生のみなさんの相談に乗りますので、くだらないことも気軽に話しかけてください。
      履修に関するご質問は所属学部。入試に関するご相談は、入学センターへお問い合わせ下さい。
    </p>
    <p class="links">大阪府東大阪市</p>
    <p class="links"><%= link_to 'instagram.com/kindaiuniversity', 'https://instagram.com/kindaiuniversity' %></p>
    <p class="links">2010年12月に登録</p>
    <%= link_to 'ツイート', new_tweet_path, class: 'action-btn' %>
    <%= link_to 'ダイレクトメッセージ', "#/", class: 'action-btn' %>
  </div>
  <div class="content-timeline">
    <div class="timeline-header">
      <%= link_to 'ツイート', '#', class: 'navigation active' %>
      <%= link_to 'ツイートと返信', '#', class: 'navigation' %>
      <%= link_to 'メディア', '#', class: 'navigation' %>
    </div>
    <% @tweets.each do |tweet| %>
      <div class="timeline-card">
        <div class="timeline-card-icon">
          <img src="https://pbs.twimg.com/profile_images/1113368983854407680/begsOPlp_400x400.jpg">
        </div>
        <div class="timeline-card-body">
          <span class="display_name">近畿大学</span>
          <span class="user_name">@kinkidaigakuPR</span>
          <time class="tweet_time" datetime="<%= tweet.tdate %>">
            ・<%= time_ago_in_words(tweet.tdate) %>
          </time>
          <p>
            <%= tweet.message %>
          </p>
          <%= link_to '表示', tweet_path(tweet.id) %>
          <%= link_to '編集', edit_tweet_path(tweet.id) %>
          <%= link_to '削除', "tweets/#{tweet.id}", method: :delete %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>Add new tweet</h1>

<% if @tweet.errors.present? %>
  <h3>エラーがあります</h3>
  <ul>
    <% @tweet.errors.full_messages.each do |e| %>
      <li><%= e %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @tweet, url: {action: :create} do |f| %>
  <%= f.label :message, '今の気持ちをツイートしよう！' %>
  <%= f.text_field :message %>
  <br>
  <%= f.submit '登録' %>
<% end %>

app/views/tweets/show.html.erb
<h1>Detail for tweet</h1>
<p>
  <strong>本文 : </strong>
  <%= @tweet.message %>
</p>
<p>
  <strong>日時 : </strong>
  <%= @tweet.tdate %>
</p>

<%= link_to 'Back', :back %>